ch16/Models/Delivery.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch16.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Delivery
    {
        public int did { get; set; }
        [DisplayName("帳號")]
        [StringLength(20, MinimumLength = 4, ErrorMessage = "帳號最少4個字，最多20個字")]
        [Required(ErrorMessage = "請輸入帳號")]
        [RegularExpression(@"^.*(?=.*\d)(?=.*[a-zA-Z]).*$", ErrorMessage = "帳號須包含英文數字")]
        public string duserid { get; set; }

        [DisplayName("密碼")]
        [DataType(DataType.Password)]
        [StringLength(20, ErrorMessage = "密碼最長20個字")]
        [RegularExpression(@"^.*(?=.*\d)(?=.*[a-zA-Z]).*$", ErrorMessage = "密碼須包含英文數字")]
        [Required(ErrorMessage = "請輸入密碼")]
        public string dpwd { get; set; }

        [DisplayName("姓名")]
        [StringLength(20, ErrorMessage = "姓名最多20個字")]
        [Required(ErrorMessage = "請輸入外送員姓名")]
        public string dname { get; set; }

        [DisplayName("手機號碼")]
        [Required(ErrorMessage = "請輸入手機")]
        [RegularExpression(@"^[09][0-9]{9}", ErrorMessage = "手機為09開頭，請輸入十個數字")]
        public string dphone { get; set; }


        public string suserid { get; set; }
        public string historydel { get; set; }
    }
}

ch16/Controllers/DeliveryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ch16.Models;

namespace ch16.Controllers
{
    public class DeliveryController : Controller
    {
        ChuHou1120Entities db = new ChuHou1120Entities();
        // GET: Delivery
        public ActionResult DemoDel()//列出外送員名單
        {            
            if (Session["Member"] == null)
            {
                return RedirectToAction("Index", "Home","_Layout");
            }
            var user = Session["Store"].ToString();
            var sto = db.StoreMember.Where(m => m.suserid == user ).FirstOrDefault();//找店
            if (sto.sdelivery == "1")
            {
                ViewBag.delopen = "開放中";
                ViewBag.openchoose = "關閉外送";
            }else if(sto.sdelivery == "2")
            {
                ViewBag.delopen = "關閉中";
                ViewBag.openchoose = "開放外送";
            }
            
            var del = db.Delivery.Where(m => m.suserid == user && m.historydel == "0").ToList();//找店的外送員
            return View("DemoDel","_LayoutMember",del);
        }
        [HttpPost]
        public ActionResult openchoose()
        {
            var user = Session["Store"].ToString();
            var sto = db.StoreMember.Where(m => m.suserid == user).FirstOrDefault();
            if (sto.sdelivery == "1")
            {
                sto.sdelivery = "2";
                db.SaveChanges();
                return RedirectToAction("DemoDel");
            }            
            sto.sdelivery = "1";
            db.SaveChanges();
            return RedirectToAction("DemoDel");
        }
        public ActionResult CreateDel()//新增外送員
        {
            if (Session["Member"] == null)
            {
                return RedirectToAction("Index", "Home", "_Layout");
            }
            return View("CreateDel", "_LayoutMember");
        }
        [HttpPost]
        public ActionResult CreateDel(Delivery NewUser,string duserid, string dpwd, string dname, string dphone,string suserid)
        {
            if (ModelState.IsValid == false)
            {
                return View("CreateDel");
            }
            var user = Session["Store"].ToString();
            var del = (from s in db.Delivery where s.duserid == NewUser.duserid  select s).FirstOrDefault();//新增的帳號
            Session["Del"] = NewUser.duserid;//存剛剛的帳號
            var d = Session["Del"].ToString();
            if(del == null)//帳號重複 
            {
                db.Delivery.Add(NewUser);
                db.SaveChanges();
                var dd = db.Delivery.Where(m => m.duserid == d).FirstOrDefault();//找剛剛的帳號資料
                dd.suserid = Session["Store"].ToString();
                dd.historydel = "0";
                db.SaveChanges();
                return RedirectToAction("DemoDel");
            }
            ViewBag.Del = "帳號重複";
            return View("CreateDel");
        }
        public ActionResult EditDel(int id)//修改外送員
        {
            if (Session["Member"] == null)
            {
                return RedirectToAction("Login", "Home", "_Layout");
            }
            var de = db.Delivery.Where(m => m.did == id).FirstOrDefault();
            return View("EditDel", de);
        }
        [HttpPost]
        public ActionResult EditDel(int id, string dname, string dphone)
        {
            var de = db.Delivery.Where(m => m.did == id).FirstOrDefault();            
            de.dname = dname;
            de.dphone = dphone;
            db.SaveChanges();
            return RedirectToAction("DemoDel");
        }
        public ActionResult DeleteDel(int id)//刪除外送員
        {
            var de = db.Delivery.Where(m => m.did == id).FirstOrDefault();
            de.historydel="1";
            db.SaveChanges();
            return RedirectToAction("DemoDel");
        }      
       
    }
}

ch16/Views/Delivery/CreateDel.cshtml
@model ch16.Models.Delivery

@{
    ViewBag.Title = "CreateDel";
}

<h2><img src="~/images/editorial-design.png" width="50" /><label color: #fff;>新增外送員資訊</label></h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })    
    @*<input type="hidden" name="suerid" value="@Session["Store"].ToString()" />*@

    <div class="form-group">
        @Html.LabelFor(model => model.duserid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.duserid, new { htmlAttributes = new { @class = "form-control", type = "text", maxlength = "20", required = "required" } })
            @Html.ValidationMessageFor(model => model.duserid, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dpwd, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dpwd, new { htmlAttributes = new { @class = "form-control", type = "password", maxlength = "20", required = "required" } })
            @Html.ValidationMessageFor(model => model.dpwd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dname, new { htmlAttributes = new { @class = "form-control", type = "text", maxlength = "20", required = "required" } })
            @Html.ValidationMessageFor(model => model.dname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dphone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dphone, new { htmlAttributes = new { @class = "form-control",type = "tel", minlength = "10", maxlength = "10", required = "required" }    })
            @Html.ValidationMessageFor(model => model.dphone, "", new { @class = "text-danger" })
        </div>
    </div>       

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="確定新增" class="btn btn-success" />
            @ViewBag.Del
        </div>        
    </div>
</div>
}

<div>
    <button type="button" class="btn btn-link" style="font-size:medium" onclick="location.href='@Url.Action("DemoDel", "Delivery")'">
        <span class="glyphicon glyphicon-hand-left"></span> 返回
    </button>
    @*@Html.ActionLink("返回", "DemoDel")*@
</div>

ch16/Views/Delivery/DelAbout.cshtml
@model ch16.Models.Delivery
@{
    ViewBag.Title = "DelAbout";
}

<h2>個人檔案</h2>
<div class="row">
    <div class="col-xs-4">
        <table class="table">
            <tr>
                <th>
                    帳號:
                </th>
                <th>
                    @Model.duserid
                </th>
            </tr>
            <tr>
                <th>
                    姓名:
                </th>
                <th>
                    @Model.dname
                </th>
            </tr>
            <tr>
                <th>
                    帳號:
                </th>
                <th>
                    @Model.dphone
                </th>
            </tr>
            <tr>
                <td></td>
                <td>@Html.ActionLink("修改資料","Edit", new { id = Model.duserid })</td>
            </tr>
        </table>
    </div>
</div>

ch16/Views/Delivery/DelIndex.cshtml
@model IEnumerable<ch16.Models.Order>

@{
    ViewBag.Title = "DelOrder";
}

<h2>目前訂單</h2>

<table class="table">
    <tr>
        <th>
            訂單日期
        </th>
        <th>
            收件人姓名
        </th>
        <th>
            電話
        </th>
        <th>
            外送地址
        </th>
        <th>
            取餐時間
        </th>
        <th>
            訂單進度
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.orderdate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.receiver)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.odate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ostatus)
            </td>

            <td>
                @Html.ActionLink("訂單詳情", "DelOrderDetail", new { id = item.oid })
            </td>
        </tr>
    }

</table>

ch16/Views/Delivery/DemoDel.cshtml
@model IEnumerable<ch16.Models.Delivery>

@{
    ViewBag.Title = "DemoDel";
}
<table>
    <tr>
        <td>
            <h4><label color: #fff;>外送 @ViewBag.delopen </label></h4>
        </td>
        <td>
            &nbsp;&nbsp;
        </td>
        <td>
            @using (Html.BeginForm("openchoose", "Delivery", FormMethod.Post))
            {
                <input type="submit" value="@ViewBag.openchoose" class="btn btn-success btn-sm" />
            }
        </td>
    </tr>    
</table>

<h2><img src="~/images/resume.png" width="50" /><label color: #fff;>外送員資訊</label></h2>
<p>
    <button type="button" class="btn btn-link" onclick="location.href='@Url.Action("CreateDel","Delivery")'">
        <span class="glyphicon glyphicon-log-in"></span> 新增外送員
    </button>
</p>@*@Html.ActionLink("新增外送員", "CreateDel")*@
<table class="table">
    <tr>
        <th>
            帳號
        </th>
        <th>
            密碼
        </th>
        <th>
            外送員姓名
        </th>
        <th>
            電話
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.duserid)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dpwd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dname)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dphone)
            </td>
            <td>
                <button type="button" class="btn btn-link" onclick="location.href='@Url.Action("EditDel", "Delivery", new { id = item.did })'">
                    <span class="glyphicon glyphicon-pencil"></span> 修改
                </button>|
                @*<button type="button" class="btn btn-link" onclick="location.href='@Url.Action("EditDel", "Delivery", new { id = item.did })'">
                    <span class="glyphicon glyphicon-trash"></span>刪除
                </button>|*@
                    @Html.ActionLink("刪除", "DeleteDel", new { id = item.did }, new { onclick = "return confirm('確定要刪除嗎?');" })               
            </td>
        </tr>
        @*@Html.ActionLink("修改", "EditDel", new { id = item.did })*@

    }
</table>

ch16/Views/Delivery/Edit.cshtml
@model ch16.Models.Delivery

@{
    ViewBag.Title = "Edit";
}

<h2>修改資料</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.did)

    <div class="form-group">
        @Html.LabelFor(model => model.duserid, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(model => model.duserid)
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dpwd, htmlAttributes: new { @class = "control-label col-md-2" }) 
        <div class="col-md-10">
            @Html.EditorFor(model => model.dpwd, new { htmlAttributes = new { @class = "form-control", type = "password", maxlength = "20", required = "required" } })
            @Html.ValidationMessageFor(model => model.dpwd, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dname, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dname, new { htmlAttributes = new { @class = "form-control", type = "text", maxlength = "20", required = "required" } })
            @Html.ValidationMessageFor(model => model.dname, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.dphone, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.dphone, new { htmlAttributes = new { @class = "form-control", type = "tel", required = "required" } })
            @Html.ValidationMessageFor(model => model.dphone, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="確定修改" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("返回", "DelAbout")
</div>

ch16/Views/Delivery/EditDel.cshtml
@model ch16.Models.Delivery

@{
    ViewBag.Title = "EditDel";
}

<h2><img src="~/images/editorial-design.png" width="50" /><label color: #fff;>修改外送員資訊</label></h2>
<p>
    
</p>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.did)

        <div class="form-group">
            @Html.LabelFor(model => model.duserid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.duserid)
            </div>
        </div>                

        <div class="form-group">
            @Html.LabelFor(model => model.dname, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dname, new { htmlAttributes = new { @class = "form-control", type = "text", maxlength = "20", required = "required" } })
                @Html.ValidationMessageFor(model => model.dname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dphone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dphone, new { htmlAttributes = new { @class = "form-control", type = "tel", minlength = "10", maxlength = "10", required = "required" } })
                @Html.ValidationMessageFor(model => model.dphone, "", new { @class = "text-danger" })
            </div>
        </div>        

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="確定修改" class="btn btn-success" />
            </div>
        </div>
    </div>
}

    <div>
        <button type="button" class="btn btn-link" style="font-size:medium" onclick="location.href='@Url.Action("DemoDel", "Delivery")'">
            <span class="glyphicon glyphicon-hand-left"></span> 返回
        </button>
        @*@Html.ActionLink("返回", "DemoDel")*@
    </div>